"""Init

Revision ID: f854de44c405
Revises: 
Create Date: 2024-02-20 22:33:44.807566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f854de44c405'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=10), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nark1', sa.Integer(), nullable=True),
    sa.Column('created1', sa.DateTime(), nullable=True),
    sa.Column('mark2', sa.Integer(), nullable=True),
    sa.Column('created2', sa.DateTime(), nullable=True),
    sa.Column('mark3', sa.Integer(), nullable=True),
    sa.Column('created3', sa.DateTime(), nullable=True),
    sa.Column('mark4', sa.Integer(), nullable=True),
    sa.Column('created4', sa.DateTime(), nullable=True),
    sa.Column('mark5', sa.Integer(), nullable=True),
    sa.Column('created5', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=150), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=200), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_name', sa.String(length=150), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups_to_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('groupstud_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['groupstud_id'], ['students.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups_to_teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groupteach_id', sa.Integer(), nullable=True),
    sa.Column('teachgroup_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['groupteach_id'], ['groups.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teachgroup_id'], ['teachers.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students_to_marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentmark_id', sa.Integer(), nullable=True),
    sa.Column('markstud_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['markstud_id'], ['marks.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studentmark_id'], ['students.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects_to_marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subjmark_id', sa.Integer(), nullable=True),
    sa.Column('marksubj_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['marksubj_id'], ['marks.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subjmark_id'], ['subjects.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects_to_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subjstud_id', sa.Integer(), nullable=True),
    sa.Column('studsubj_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['studsubj_id'], ['students.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subjstud_id'], ['subjects.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers_to_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers_to_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teachersub_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teachersub_id'], ['teachers.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teachers_to_subjects')
    op.drop_table('teachers_to_students')
    op.drop_table('subjects_to_students')
    op.drop_table('subjects_to_marks')
    op.drop_table('students_to_marks')
    op.drop_table('groups_to_teachers')
    op.drop_table('groups_to_students')
    op.drop_table('teachers')
    op.drop_table('subjects')
    op.drop_table('students')
    op.drop_table('marks')
    op.drop_table('groups')
    # ### end Alembic commands ###
